### ISSUE TITLE
BACK END - QR code 

### ISSUE THREAD

**Issue by aaandri98** [aaandri98/FablabNetworkMobile#11]
I have got an idea in how to develop this part: in order to optimize the inventory management, we could bind to each machine inserted by a fablab a QR code; in this cose should be represented all the details of the machine.

then, ideally this qr code can be printed and sticked on the machine. In order to book it, the user can search manually the machine in the search functionality; otherwise, he could just scan the QR code and book the machine.

This QR Code functionality can also be integrated in the user recognition: each user can show (and customize?) his own qr code which can be scanned by the fablab admins in order to speed up functionalities (subscibtions, payments..)

**Comment by hell0fri3nd** [comment]
I think it is a great idea. When could we generate this qr code? In the page when a new machine is inserted?

**Comment by aaandri98** [comment]
it could be.. we can create the qr code in an automatic way, then it's your choice if use it or not

we should just create the recognizer, which i don't know how it works

my idea is to have a way to speed up operations in which you need to insert data

**Comment by hell0fri3nd** [comment]
However we force the user to be in a fablab when he wants to book a machine. Without the qr code you could not book from home for example.

**Comment by aaandri98** [comment]
no, we use both the methods

the qr code is a function only available in the mobile version, otherwise it is a perfect copy of the web one

**Comment by matteo-messmer** [comment]
I think all of this is really interesting
