### ISSUE TITLE
BACK END - Camera feature

### ISSUE THREAD

**Issue by hell0fri3nd** [aaandri98/FablabNetworkMobile#6]
Used for: 

- [ ] Profile/cover picture
- [ ] Project picture

**Comment by aaandri98** [comment]
can be an option, not read very much

https://github.com/react-native-community/react-native-camera

**Comment by aaandri98** [comment]
https://docs.expo.io/versions/latest/sdk/camera/

this one with expo, we saw that using its plugin is better than react-native ones

**Comment by aaandri98** [comment]
can be added the #11 funcitonality, if you are happy with this
